cat > configs/turkceos_defconfig <<EOF
BR2_x86_64=y
BR2_TOOLCHAIN_BUILDROOT_GLIBC=y
BR2_TARGET_GENERIC_HOSTNAME="turkceos"
BR2_TARGET_GENERIC_ISSUE="TurkceOS"
BR2_PACKAGE_PYTHON3=y
BR2_PACKAGE_PYTHON3_TKINTER=y
BR2_PACKAGE_XORG7=y
BR2_PACKAGE_XINIT=y
BR2_TARGET_ROOTFS_ISO9660=y
BR2_ROOTFS_OVERLAY="board/turkceos/rootfs-overlay"
EOF

          make turkceos_defconfig
          make

      - name: ISO yükle
        uses: actions/upload-artifact@v3
        with:
          name: turkceos
          path: buildroot/output/images/
